# Generated by Django 5.2.1 on 2025-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_diet_calories_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='calories_per_day',
            field=models.IntegerField(),
        ),
    ]
