# Generated by Django 5.2.1 on 2025-06-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_diet_calories_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='updated_at',
        ),
    ]
